# Generated by Django 4.1.2 on 2023-02-09 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='subtitile',
            new_name='subtitle',
        ),
    ]
